name: cloudwalk_location
description: "Display the current location"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: 2.6.0
  geolocator: ^7.1.0
  get_it: ^7.2.0
  dio: ^5.4.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  dart_either: 1.0.0
  hive: 2.2.3
  path_provider: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  http_mock_adapter: ^0.6.0
  mockito: ^5.4.4
  json_serializable:
  

flutter:
  uses-material-design: true

